// Copyright (c) 2020 Bojan Zivanovic and contributors
// SPDX-License-Identifier: MIT

package address

var formats = map[string]Format{
	"ZZ": {
		Layout:   "%1\n%2\n%3\n%L",
		Required: []Field{FieldLine1, FieldLocality},
	},
	"AC": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "ASCN 1ZZ",
	},
	"AD": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "AD[1-7]0\\d",
	},
	"AE": {
		Locale:     Locale{Language: "ar"},
		Layout:     "%1\n%2\n%3\n%R",
		Required:   []Field{FieldLine1, FieldRegion},
		RegionType: RegionTypeEmirate,
		Regions: NewRegionMap(
			"AZ", "Abu Dhabi", "AJ", "Ajmān", "DU", "Dubai",
			"FU", "Fujairah", "RK", "Ras Al Khaimah", "SH", "Sharjah",
			"UQ", "Umm Al Quwain",
		),
		LocalRegions: NewRegionMap(
			"AZ", "أبو ظبي", "SH", "الشارقة", "FU", "الفجيرة",
			"UQ", "ام القيوين", "DU", "دبي", "RK", "رأس الخيمة",
			"AJ", "عجمان",
		),
	},
	"AF": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"AG": {
		Layout:   "%1\n%2\n%3\n%L",
		Required: []Field{FieldLine1},
	},
	"AI": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "(?:AI-)?2640",
	},
	"AL": {
		Layout:            "%1\n%2\n%3\n%P\n%L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"AM": {
		Locale:            Locale{Language: "hy"},
		Layout:            "%1\n%2\n%3\n%P\n%L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "(?:37)?\\d{4}",
		Regions: NewRegionMap(
			"AG", "Aragatsotn", "AR", "Ararat", "AV", "Armavir",
			"GR", "Gegharkunik", "KT", "Kotayk", "LO", "Lori",
			"SH", "Shirak", "SU", "Syunik", "TV", "Tavush",
			"VD", "Vayots Dzor", "ER", "Yerevan",
		),
		LocalRegions: NewRegionMap(
			"AG", "Արագածոտն", "AR", "Արարատ", "AV", "Արմավիր",
			"GR", "Գեղարքունիք", "ER", "Երևան", "LO", "Լոռի",
			"KT", "Կոտայք", "SH", "Շիրակ", "SU", "Սյունիք",
			"VD", "Վայոց ձոր", "TV", "Տավուշ",
		),
	},
	"AR": {
		Layout:            "%1\n%2\n%3\n%P %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?",
		Regions: NewRegionMap(
			"B", "Buenos Aires", "K", "Catamarca", "H", "Chaco",
			"U", "Chubut", "C", "Ciudad Autónoma de Buenos Aires", "X", "Córdoba",
			"W", "Corrientes", "E", "Entre Ríos", "P", "Formosa",
			"Y", "Jujuy", "L", "La Pampa", "F", "La Rioja",
			"M", "Mendoza", "N", "Misiones", "Q", "Neuquén",
			"R", "Río Negro", "A", "Salta", "J", "San Juan",
			"D", "San Luis", "Z", "Santa Cruz", "S", "Santa Fe",
			"G", "Santiago del Estero", "V", "Tierra del Fuego", "T", "Tucumán",
		),
	},
	"AS": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(96799)(?:[ \\-](\\d{4}))?",
	},
	"AT": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"AU": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		LocalityType:      LocalityTypeSuburb,
		PostalCodePattern: "\\d{4}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"ACT", "Australian Capital Territory", "NSW", "New South Wales", "NT", "Northern Territory",
			"QLD", "Queensland", "SA", "South Australia", "TAS", "Tasmania",
			"VIC", "Victoria", "WA", "Western Australia",
		),
	},
	"AX": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "22\\d{3}",
	},
	"AZ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"BA": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"BB": {
		Layout:            "%1\n%2\n%3\n%L, %R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		RegionType:        RegionTypeParish,
		PostalCodePattern: "BB\\d{5}",
	},
	"BD": {
		Layout:            "%1\n%2\n%3\n%L - %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"BE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"BG": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"BH": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "(?:\\d|1[0-2])\\d{2}",
	},
	"BL": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78][01]\\d{2}",
	},
	"BM": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "[A-Z]{2} ?[A-Z0-9]{2}",
	},
	"BN": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "[A-Z]{2} ?\\d{4}",
	},
	"BR": {
		Layout:            "%1\n%2\n%3\n%S\n%L-%R\n%P",
		Required:          []Field{FieldLine1, FieldRegion, FieldLocality, FieldPostalCode},
		RegionType:        RegionTypeState,
		SublocalityType:   SublocalityTypeNeighborhood,
		PostalCodePattern: "\\d{5}-?\\d{3}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AC", "Acre", "AL", "Alagoas", "AP", "Amapá",
			"AM", "Amazonas", "BA", "Bahia", "CE", "Ceará",
			"DF", "Distrito Federal", "ES", "Espírito Santo", "GO", "Goiás",
			"MA", "Maranhão", "MT", "Mato Grosso", "MS", "Mato Grosso do Sul",
			"MG", "Minas Gerais", "PA", "Pará", "PB", "Paraíba",
			"PR", "Paraná", "PE", "Pernambuco", "PI", "Piauí",
			"RJ", "Rio de Janeiro", "RN", "Rio Grande do Norte", "RS", "Rio Grande do Sul",
			"RO", "Rondônia", "RR", "Roraima", "SC", "Santa Catarina",
			"SP", "São Paulo", "SE", "Sergipe", "TO", "Tocantins",
		),
	},
	"BS": {
		Layout:     "%1\n%2\n%3\n%L, %R",
		Required:   []Field{FieldLine1, FieldLocality},
		RegionType: RegionTypeIsland,
	},
	"BT": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"BY": {
		Layout:            "%1\n%2\n%3\n%P, %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"CA": {
		Locale:            Locale{Language: "fr"},
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		PostalCodePattern: "[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z] ?\\d[ABCEGHJ-NPRSTV-Z]\\d",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AB", "Alberta", "BC", "British Columbia", "MB", "Manitoba",
			"NB", "New Brunswick", "NL", "Newfoundland and Labrador", "NT", "Northwest Territories",
			"NS", "Nova Scotia", "NU", "Nunavut", "ON", "Ontario",
			"PE", "Prince Edward Island", "QC", "Quebec", "SK", "Saskatchewan",
			"YT", "Yukon",
		),
		LocalRegions: NewRegionMap(
			"AB", "Alberta", "BC", "Colombie-Britannique", "MB", "Manitoba",
			"NB", "Nouveau-Brunswick", "NL", "Terre-Neuve-et-Labrador", "NT", "Territoires du Nord-Ouest",
			"NS", "Nouvelle-Écosse", "NU", "Nunavut", "ON", "Ontario",
			"PE", "Île-du-Prince-Édouard", "QC", "Québec", "SK", "Saskatchewan",
			"YT", "Yukon",
		),
	},
	"CC": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "6799",
	},
	"CH": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"CL": {
		Layout:            "%1\n%2\n%3\n%P %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{7}",
		Regions: NewRegionMap(
			"AI", "Aisén del General Carlos Ibáñez del Campo", "AN", "Antofagasta", "AR", "Araucanía",
			"AP", "Arica y Parinacota", "AT", "Atacama", "BI", "Biobío",
			"CO", "Coquimbo", "LI", "Libertador General Bernardo O'Higgins", "LL", "Los Lagos",
			"LR", "Los Ríos", "MA", "Magallanes y de la Antártica Chilena", "ML", "Maule",
			"RM", "Metropolitana de Santiago", "NB", "Ñuble", "TA", "Tarapacá",
			"VS", "Valparaíso",
		),
	},
	"CN": {
		Locale:            Locale{Language: "zh"},
		Layout:            "%1\n%2\n%3\n%S\n%L\n%R, %P",
		LocalLayout:       "%P\n%R%L%S\n%1\n%2\n%3",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		SublocalityType:   SublocalityTypeDistrict,
		PostalCodePattern: "\\d{6}",
		Regions: NewRegionMap(
			"AH", "Anhui Sheng", "BJ", "Beijing Shi", "CQ", "Chongqing Shi",
			"FJ", "Fujian Sheng", "GS", "Gansu Sheng", "GD", "Guangdong Sheng",
			"GX", "Guangxi Zhuangzu Zizhiqu", "GZ", "Guizhou Sheng", "HI", "Hainan Sheng",
			"HE", "Hebei Sheng", "HL", "Heilongjiang Sheng", "HA", "Henan Sheng",
			"HK", "Hong Kong SAR", "HB", "Hubei Sheng", "HN", "Hunan Sheng",
			"JS", "Jiangsu Sheng", "JX", "Jiangxi Sheng", "JL", "Jilin Sheng",
			"LN", "Liaoning Sheng", "MO", "Macao SAR", "NM", "Neimenggu Zizhiqu",
			"NX", "Ningxia Huizu Zizhiqu", "QH", "Qinghai Sheng", "SN", "Shaanxi Sheng",
			"SD", "Shandong Sheng", "SH", "Shanghai Shi", "SX", "Shanxi Sheng",
			"SC", "Sichuan Sheng", "TW", "Taiwan Sheng", "TJ", "Tianjin Shi",
			"XJ", "Xinjiang Weiwu'er Zizhiqu", "XZ", "Xizang Zizhiqu", "YN", "Yunnan Sheng",
			"ZJ", "Zhejiang Sheng",
		),
		LocalRegions: NewRegionMap(
			"AH", "安徽省", "MO", "澳门", "BJ", "北京市",
			"CQ", "重庆市", "FJ", "福建省", "GS", "甘肃省",
			"GD", "广东省", "GX", "广西", "GZ", "贵州省",
			"HI", "海南省", "HE", "河北省", "HA", "河南省",
			"HL", "黑龙江省", "HB", "湖北省", "HN", "湖南省",
			"JL", "吉林省", "JS", "江苏省", "JX", "江西省",
			"LN", "辽宁省", "NM", "内蒙古", "NX", "宁夏",
			"QH", "青海省", "SD", "山东省", "SX", "山西省",
			"SN", "陕西省", "SH", "上海市", "SC", "四川省",
			"TW", "台湾", "TJ", "天津市", "XZ", "西藏",
			"HK", "香港", "XJ", "新疆", "YN", "云南省",
			"ZJ", "浙江省",
		),
	},
	"CO": {
		Layout:            "%1\n%2\n%3\n%L, %R, %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType:        RegionTypeDepartment,
		PostalCodePattern: "\\d{6}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AMA", "Amazonas", "ANT", "Antioquia", "ARA", "Arauca",
			"ATL", "Atlántico", "BOL", "Bolívar", "BOY", "Boyacá",
			"CAL", "Caldas", "CAQ", "Caquetá", "CAS", "Casanare",
			"CAU", "Cauca", "CES", "Cesar", "COR", "Córdoba",
			"CUN", "Cundinamarca", "CHO", "Chocó", "DC", "Distrito Capital de Bogotá",
			"GUA", "Guanía", "GUV", "Guaviare", "HUI", "Huila",
			"LAG", "La Guajira", "MAG", "Magdalena", "MET", "Meta",
			"NAR", "Nariño", "NSA", "Norte de Santander", "PUT", "Putumayo",
			"QUI", "Quindío", "RIS", "Risaralda", "SAP", "San Andrés, Providencia y Santa Catalina",
			"SAN", "Santander", "SUC", "Sucre", "TOL", "Tolima",
			"VAC", "Valle del Cauca", "VAU", "Vaupés", "VID", "Vichada",
		),
	},
	"CR": {
		Layout:            "%1\n%2\n%3\n%R, %L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		PostalCodePattern: "\\d{4,5}|\\d{3}-\\d{4}",
	},
	"CU": {
		Layout:            "%1\n%2\n%3\n%L %R\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"15", "Artemisa", "09", "Camagüey", "08", "Ciego de Ávila",
			"06", "Cienfuegos", "12", "Granma", "14", "Guantánamo",
			"11", "Holguín", "99", "Isla de la Juventud", "03", "La Habana",
			"10", "Las Tunas", "04", "Matanzas", "16", "Mayabeque",
			"01", "Pinar del Río", "07", "Sancti Spíritus", "13", "Santiago de Cuba",
			"05", "Villa Clara",
		),
	},
	"CV": {
		Layout:            "%1\n%2\n%3\n%P %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		RegionType:        RegionTypeIsland,
		PostalCodePattern: "\\d{4}",
	},
	"CX": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "6798",
	},
	"CY": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"CZ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{3} ?\\d{2}",
	},
	"DE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{5}",
	},
	"DK": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"DO": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"DZ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"EC": {
		Layout:            "%1\n%2\n%3\n%P\n%L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"EE": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		RegionType:        RegionTypeCounty,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"37", "Harjumaa", "39", "Hiiumaa", "45", "Ida-Virumaa",
			"50", "Jõgevamaa", "52", "Järvamaa", "56", "Läänemaa",
			"60", "Lääne-Virumaa", "64", "Põlvamaa", "68", "Pärnumaa",
			"71", "Raplamaa", "74", "Saaremaa", "79", "Tartumaa",
			"81", "Valgamaa", "84", "Viljandimaa", "87", "Võrumaa",
		),
	},
	"EG": {
		Locale:            Locale{Language: "ar"},
		Layout:            "%1\n%2\n%3\n%L\n%R\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"ALX", "Alexandria", "ASN", "Aswan", "AST", "Asyut",
			"BH", "Beheira", "BNS", "Beni Suef", "C", "Cairo",
			"DK", "Dakahlia", "DT", "Damietta", "FYM", "Faiyum",
			"GH", "Gharbia", "GZ", "Giza", "IS", "Ismailia",
			"KFS", "Kafr el-Sheikh", "LX", "Luxor", "MT", "Matruh",
			"MN", "Minya", "MNF", "Monufia", "WAD", "New Valley",
			"SIN", "North Sinai", "PTS", "Port Said", "KB", "Qalyubia",
			"KN", "Qena", "BA", "Red Sea", "SHR", "Sharqia",
			"SHG", "Sohag", "JS", "South Sinai", "SUZ", "Suez",
		),
		LocalRegions: NewRegionMap(
			"ASN", "أسوان", "AST", "أسيوط", "ALX", "الإسكندرية",
			"IS", "الإسماعيلية", "LX", "الأقصر", "BA", "البحر الأحمر",
			"BH", "البحيرة", "GZ", "الجيزة", "DK", "الدقهلية",
			"SUZ", "السويس", "SHR", "الشرقية", "GH", "الغربية",
			"FYM", "الفيوم", "C", "القاهرة", "KB", "القليوبية",
			"MNF", "المنوفية", "MN", "المنيا", "WAD", "الوادي الجديد",
			"BNS", "بني سويف", "PTS", "بورسعيد", "JS", "جنوب سيناء",
			"DT", "دمياط", "SHG", "سوهاج", "SIN", "شمال سيناء",
			"KN", "قنا", "KFS", "كفر الشيخ", "MT", "مطروح",
		),
	},
	"EH": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"ES": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"C", "A Coruña", "VI", "Alava", "AB", "Albacete",
			"A", "Alicante", "AL", "Almería", "O", "Asturias",
			"AV", "Ávila", "BA", "Badajoz", "PM", "Baleares",
			"B", "Barcelona", "BU", "Burgos", "CC", "Cáceres",
			"CA", "Cádiz", "S", "Cantabria", "CS", "Castellón",
			"CE", "Ceuta", "CR", "Ciudad Real", "CO", "Córdoba",
			"CU", "Cuenca", "GI", "Girona", "GR", "Granada",
			"GU", "Guadalajara", "SS", "Guipúzcoa", "H", "Huelva",
			"HU", "Huesca", "J", "Jaén", "LO", "La Rioja",
			"GC", "Las Palmas", "LE", "León", "L", "Lleida",
			"LU", "Lugo", "M", "Madrid", "MA", "Málaga",
			"ML", "Melilla", "MU", "Murcia", "NA", "Navarra",
			"OR", "Ourense", "P", "Palencia", "PO", "Pontevedra",
			"SA", "Salamanca", "TF", "Santa Cruz de Tenerife", "SG", "Segovia",
			"SE", "Sevilla", "SO", "Soria", "T", "Tarragona",
			"TE", "Teruel", "TO", "Toledo", "V", "Valencia",
			"VA", "Valladolid", "BI", "Vizcaya", "ZA", "Zamora",
			"Z", "Zaragoza",
		),
	},
	"ET": {
		Layout:            "%1\n%2\n%3\n%P %L",
		PostalCodePattern: "\\d{4}",
	},
	"FI": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{5}",
	},
	"FK": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "FIQQ 1ZZ",
	},
	"FM": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(9694[1-4])(?:[ \\-](\\d{4}))?",
	},
	"FO": {
		Layout:            "%1\n%2\n%3\n%P %L",
		PostalCodePattern: "\\d{3}",
	},
	"FR": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{2} ?\\d{3}",
	},
	"GB": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		LocalityType:      LocalityTypePostTown,
		PostalCodePattern: "GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}",
	},
	"GE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"GF": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78]3\\d{2}",
	},
	"GG": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "GY\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}",
	},
	"GI": {
		Layout:            "%1\n%2\n%3\n%P",
		Required:          []Field{FieldLine1},
		PostalCodePattern: "GX11 1AA",
	},
	"GL": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "39\\d{2}",
	},
	"GN": {
		Layout:            "%P %1\n%2\n%3 %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{3}",
	},
	"GP": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78][01]\\d{2}",
	},
	"GR": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{3} ?\\d{2}",
	},
	"GS": {
		Layout:            "%1\n%2\n%3\n\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "SIQQ 1ZZ",
	},
	"GT": {
		Layout:            "%1\n%2\n%3\n%P- %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"GU": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?",
	},
	"GW": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"HK": {
		Locale:       Locale{Language: "zh", Script: "Hant"},
		Layout:       "%1\n%2\n%3\n%L\n%R",
		LocalLayout:  "%R\n%L\n%1\n%2\n%3",
		Required:     []Field{FieldLine1, FieldRegion},
		RegionType:   RegionTypeArea,
		LocalityType: LocalityTypeDistrict,
		// HK areas have no ISO codes assigned.
		Regions: NewRegionMap(
			"Kowloon", "Kowloon",
			"Hong Kong Island", "Hong Kong Island",
			"New Territories", "New Territories",
		),
		LocalRegions: NewRegionMap(
			"Kowloon", "九龍",
			"Hong Kong Island", "香港島",
			"New Territories", "新界",
		),
	},
	"HM": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"HN": {
		Layout:            "%1\n%2\n%3\n%L, %R\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType:        RegionTypeDepartment,
		PostalCodePattern: "\\d{5}",
	},
	"HR": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"HT": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"HU": {
		Layout:            " %L\n%1\n%2\n%3\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"ID": {
		Layout:            "%1\n%2\n%3\n%L\n%R %P",
		Required:          []Field{FieldLine1, FieldRegion},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"AC", "Aceh", "BA", "Bali", "BT", "Banten",
			"BE", "Bengkulu", "YO", "D.I. Yogyakarta", "JK", "DKI Jakarta",
			"GO", "Gorontalo", "JA", "Jambi", "JB", "Jawa Barat",
			"JT", "Jawa Tengah", "JI", "Jawa Timur", "KB", "Kalimantan Barat",
			"KS", "Kalimantan Selatan", "KT", "Kalimantan Tengah", "KI", "Kalimantan Timur",
			"KU", "Kalimantan Utara", "BB", "Kepulauan Bangka Belitung", "KR", "Kepulauan Riau",
			"LA", "Lampung", "MA", "Maluku", "MU", "Maluku Utara",
			"NB", "Nusa Tenggara Barat", "NT", "Nusa Tenggara Timur", "PA", "Papua",
			"PB", "Papua Barat", "RI", "Riau", "SR", "Sulawesi Barat",
			"SN", "Sulawesi Selatan", "ST", "Sulawesi Tengah", "SG", "Sulawesi Tenggara",
			"SA", "Sulawesi Utara", "SB", "Sumatera Barat", "SS", "Sumatera Selatan",
			"SU", "Sumatera Utara",
		),
	},
	"IE": {
		Layout:            "%1\n%2\n%3\n%S\n%L\n%R\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		RegionType:        RegionTypeCounty,
		SublocalityType:   SublocalityTypeTownland,
		PostalCodeType:    PostalCodeTypeEir,
		PostalCodePattern: "[\\dA-Z]{3} ?[\\dA-Z]{4}",
		Regions: NewRegionMap(
			"CW", "Co Carlow", "CN", "Co Cavan", "CE", "Co Clare",
			"CO", "Co Cork", "DL", "Co Donegal", "D", "Co Dublin",
			"D1", "Dublin 1", "D2", "Dublin 2", "D3", "Dublin 3",
			"D4", "Dublin 4", "D5", "Dublin 5", "D6", "Dublin 6",
			"D6W", "Dublin 6w", "D7", "Dublin 7", "D8", "Dublin 8",
			"D9", "Dublin 9", "D10", "Dublin 10", "D11", "Dublin 11",
			"D12", "Dublin 12", "D13", "Dublin 13", "D14", "Dublin 14",
			"D15", "Dublin 15", "D16", "Dublin 16", "D17", "Dublin 17",
			"D18", "Dublin 18", "D19", "Dublin 19", "D20", "Dublin 20",
			"D21", "Dublin 21", "D22", "Dublin 22", "D23", "Dublin 23",
			"D24", "Dublin 24", "G", "Co Galway", "KY", "Co Kerry",
			"KE", "Co Kildare", "KK", "Co Kilkenny", "LS", "Co Laois",
			"LM", "Co Leitrim", "LK", "Co Limerick", "LD", "Co Longford",
			"LH", "Co Louth", "MO", "Co Mayo", "MH", "Co Meath",
			"MN", "Co Monaghan", "OY", "Co Offaly", "RN", "Co Roscommon",
			"SO", "Co Sligo", "TA", "Co Tipperary", "WD", "Co Waterford",
			"WH", "Co Westmeath", "WX", "Co Wexford", "WW", "Co Wicklow",
		),
	},
	"IL": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}(?:\\d{2})?",
	},
	"IM": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "IM\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}",
	},
	"IN": {
		Layout:            "%1\n%2\n%3\n%L %P\n%R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypePin,
		PostalCodePattern: "\\d{6}",
		Regions: NewRegionMap(
			"AN", "Andaman & Nicobar", "AP", "Andhra Pradesh", "AR", "Arunachal Pradesh",
			"AS", "Assam", "BR", "Bihar", "CH", "Chandigarh",
			"CT", "Chhattisgarh", "DH", "Dadra & Nagar Haveli & Daman & Diu",
			"DL", "Delhi", "GA", "Goa", "GJ", "Gujarat",
			"HR", "Haryana", "HP", "Himachal Pradesh", "JK", "Jammu & Kashmir",
			"JH", "Jharkhand", "KA", "Karnataka", "KL", "Kerala",
			"LA", "Ladakh", "LD", "Lakshadweep", "MP", "Madhya Pradesh",
			"MH", "Maharashtra", "MN", "Manipur", "ML", "Meghalaya",
			"MZ", "Mizoram", "NL", "Nagaland", "OR", "Odisha",
			"PY", "Puducherry", "PB", "Punjab", "RJ", "Rajasthan",
			"SK", "Sikkim", "TN", "Tamil Nadu", "TG", "Telangana",
			"TR", "Tripura", "UP", "Uttar Pradesh", "UT", "Uttarakhand",
			"WB", "West Bengal",
		),
	},
	"IO": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "BBND 1ZZ",
	},
	"IQ": {
		Layout:            "%1\n%2\n%3\n%L, %R\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		PostalCodePattern: "\\d{5}",
	},
	"IR": {
		Layout:            "%R\n%L, %S\n%1\n%2\n%3\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		SublocalityType:   SublocalityTypeNeighborhood,
		PostalCodePattern: "\\d{5}-?\\d{5}",
	},
	"IS": {
		Layout:            "%1\n%2\n%3\n%P %L",
		PostalCodePattern: "\\d{3}",
	},
	"IT": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		PostalCodePattern: "\\d{5}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AG", "Agrigento", "AL", "Alessandria", "AN", "Ancona",
			"AO", "Aosta", "AR", "Arezzo", "AP", "Ascoli Piceno",
			"AT", "Asti", "AV", "Avellino", "BA", "Bari",
			"BT", "Barletta-Andria-Trani", "BL", "Belluno", "BN", "Benevento",
			"BG", "Bergamo", "BI", "Biella", "BO", "Bologna",
			"BZ", "Bolzano", "BS", "Brescia", "BR", "Brindisi",
			"CA", "Cagliari", "CL", "Caltanissetta", "CB", "Campobasso",
			"CE", "Caserta", "CT", "Catania", "CZ", "Catanzaro",
			"CH", "Chieti", "CO", "Como", "CS", "Cosenza",
			"CR", "Cremona", "KR", "Crotone", "CN", "Cuneo",
			"EN", "Enna", "FM", "Fermo", "FE", "Ferrara",
			"FI", "Firenze", "FG", "Foggia", "FC", "Forlì-Cesena",
			"FR", "Frosinone", "GE", "Genova", "GO", "Gorizia",
			"GR", "Grosseto", "IM", "Imperia", "IS", "Isernia",
			"AQ", "L'Aquila", "SP", "La Spezia", "LT", "Latina",
			"LE", "Lecce", "LC", "Lecco", "LI", "Livorno",
			"LO", "Lodi", "LU", "Lucca", "MC", "Macerata",
			"MN", "Mantova", "MS", "Massa-Carrara", "MT", "Matera",
			"ME", "Messina", "MI", "Milano", "MO", "Modena",
			"MB", "Monza e Brianza", "NA", "Napoli", "NO", "Novara",
			"NU", "Nuoro", "OR", "Oristano", "PD", "Padova",
			"PA", "Palermo", "PR", "Parma", "PV", "Pavia",
			"PG", "Perugia", "PU", "Pesaro e Urbino", "PE", "Pescara",
			"PC", "Piacenza", "PI", "Pisa", "PT", "Pistoia",
			"PN", "Pordenone", "PZ", "Potenza", "PO", "Prato",
			"RG", "Ragusa", "RA", "Ravenna", "RC", "Reggio Calabria",
			"RE", "Reggio Emilia", "RI", "Rieti", "RN", "Rimini",
			"RM", "Roma", "RO", "Rovigo", "SA", "Salerno",
			"SS", "Sassari", "SV", "Savona", "SI", "Siena",
			"SR", "Siracusa", "SO", "Sondrio", "SU", "Sud Sardegna",
			"TA", "Taranto", "TE", "Teramo", "TR", "Terni",
			"TO", "Torino", "TP", "Trapani", "TN", "Trento",
			"TV", "Treviso", "TS", "Trieste", "UD", "Udine",
			"VA", "Varese", "VE", "Venezia", "VB", "Verbano-Cusio-Ossola",
			"VC", "Vercelli", "VR", "Verona", "VV", "Vibo Valentia",
			"VI", "Vicenza", "VT", "Viterbo",
		),
	},
	"JE": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "JE\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}",
	},
	"JM": {
		Layout:     "%1\n%2\n%3\n%L\n%R",
		Required:   []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType: RegionTypeParish,
		Regions: NewRegionMap(
			"13", "Clarendon", "09", "Hanover", "01", "Kingston",
			"12", "Manchester", "04", "Portland", "02", "St. Andrew",
			"06", "St. Ann", "14", "St. Catherine", "11", "St. Elizabeth",
			"08", "St. James", "05", "St. Mary", "03", "St. Thomas",
			"07", "Trelawny", "10", "Westmoreland",
		),
	},
	"JO": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"JP": {
		Locale:            Locale{Language: "ja"},
		Layout:            "%1\n%2\n%3\n%L, %R\n%P",
		LocalLayout:       "〒%P\n%R%L\n%1\n%2\n%3",
		Required:          []Field{FieldLine1, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypePrefecture,
		PostalCodePattern: "\\d{3}-?\\d{4}",
		Regions: NewRegionMap(
			"23", "Aichi", "05", "Akita", "02", "Aomori",
			"12", "Chiba", "38", "Ehime", "18", "Fukui",
			"40", "Fukuoka", "07", "Fukushima", "21", "Gifu",
			"10", "Gunma", "34", "Hiroshima", "01", "Hokkaido",
			"28", "Hyogo", "08", "Ibaraki", "17", "Ishikawa",
			"03", "Iwate", "37", "Kagawa", "46", "Kagoshima",
			"14", "Kanagawa", "39", "Kochi", "43", "Kumamoto",
			"26", "Kyoto", "24", "Mie", "04", "Miyagi",
			"45", "Miyazaki", "20", "Nagano", "42", "Nagasaki",
			"29", "Nara", "15", "Niigata", "44", "Oita",
			"33", "Okayama", "47", "Okinawa", "27", "Osaka",
			"41", "Saga", "11", "Saitama", "25", "Shiga",
			"32", "Shimane", "22", "Shizuoka", "09", "Tochigi",
			"36", "Tokushima", "13", "Tokyo", "31", "Tottori",
			"16", "Toyama", "30", "Wakayama", "06", "Yamagata",
			"35", "Yamaguchi", "19", "Yamanashi",
		),
		LocalRegions: NewRegionMap(
			"01", "北海道", "02", "青森県", "03", "岩手県",
			"04", "宮城県", "05", "秋田県", "06", "山形県",
			"07", "福島県", "08", "茨城県", "09", "栃木県",
			"10", "群馬県", "11", "埼玉県", "12", "千葉県",
			"13", "東京都", "14", "神奈川県", "15", "新潟県",
			"16", "富山県", "17", "石川県", "18", "福井県",
			"19", "山梨県", "20", "長野県", "21", "岐阜県",
			"22", "静岡県", "23", "愛知県", "24", "三重県",
			"25", "滋賀県", "26", "京都府", "27", "大阪府",
			"28", "兵庫県", "29", "奈良県", "30", "和歌山県",
			"31", "鳥取県", "32", "島根県", "33", "岡山県",
			"34", "広島県", "35", "山口県", "36", "徳島県",
			"37", "香川県", "38", "愛媛県", "39", "高知県",
			"40", "福岡県", "41", "佐賀県", "42", "長崎県",
			"43", "熊本県", "44", "大分県", "45", "宮崎県",
			"46", "鹿児島県", "47", "沖縄県",
		),
	},
	"KE": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"KG": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"KH": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5,6}",
	},
	"KI": {
		Layout:     "%1\n%2\n%3\n%R\n%L",
		Required:   []Field{FieldLine1, FieldLocality},
		RegionType: RegionTypeIsland,
	},
	"KN": {
		Layout:     "%1\n%2\n%3\n%L, %R",
		Required:   []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType: RegionTypeIsland,
	},
	"KP": {
		Locale:      Locale{Language: "ko"},
		Layout:      "%1\n%2\n%3\n%L\n%R, %P",
		LocalLayout: "%P\n%R\n%L\n%1\n%2\n%3",
		Required:    []Field{FieldLine1, FieldLocality},
	},
	"KR": {
		Locale:            Locale{Language: "ko"},
		Layout:            "%1\n%2\n%3\n%S\n%L\n%R\n%P",
		LocalLayout:       "%R %L%S\n%1\n%2\n%3",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeDoSi,
		SublocalityType:   SublocalityTypeDistrict,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"26", "Busan", "43", "Chungcheongbuk-do", "44", "Chungcheongnam-do",
			"27", "Daegu", "30", "Daejeon", "42", "Gangwon-do",
			"41", "Gyeonggi-do", "47", "Gyeongsangbuk-do", "48", "Gyeongsangnam-do",
			"29", "Gwangju", "28", "Incheon", "49", "Jeju-do",
			"45", "Jeollabuk-do", "46", "Jeollanam-do", "50", "Sejong",
			"11", "Seoul", "31", "Ulsan",
		),
		LocalRegions: NewRegionMap(
			"42", "강원", "41", "경기", "48", "경남",
			"47", "경북", "29", "광주", "27", "대구",
			"30", "대전", "26", "부산", "11", "서울",
			"50", "세종", "31", "울산", "28", "인천",
			"46", "전남", "45", "전북", "49", "제주",
			"44", "충남", "43", "충북",
		),
	},
	"KW": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"KY": {
		Layout:            "%1\n%2\n%3\n%R %P",
		Required:          []Field{FieldLine1, FieldRegion},
		RegionType:        RegionTypeIsland,
		PostalCodePattern: "KY\\d-\\d{4}",
	},
	"KZ": {
		Layout:            "%P\n%R\n%L\n%1\n%2\n%3",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"LA": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"LB": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "(?:\\d{4})(?: ?(?:\\d{4}))?",
	},
	"LI": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "948[5-9]|949[0-8]",
	},
	"LK": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"LR": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"LS": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{3}",
	},
	"LT": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		RegionType:        RegionTypeCounty,
		PostalCodePattern: "\\d{5}",
	},
	"LU": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"LV": {
		Layout:            "%1\n%2\n%3\n%L, %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "LV-\\d{4}",
	},
	"MA": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"MC": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "980\\d{2}",
	},
	"MD": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"ME": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "8\\d{4}",
	},
	"MF": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78][01]\\d{2}",
	},
	"MG": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{3}",
	},
	"MH": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(969[67]\\d)(?:[ \\-](\\d{4}))?",
	},
	"MK": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"MM": {
		Layout:            "%1\n%2\n%3\n%L, %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"MN": {
		Layout:            "%1\n%2\n%3\n%L\n%R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"MO": {
		Layout:   "%1\n%2\n%3",
		Required: []Field{FieldLine1},
	},
	"MP": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(9695[012])(?:[ \\-](\\d{4}))?",
	},
	"MQ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78]2\\d{2}",
	},
	"MT": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "[A-Z]{3} ?\\d{2,4}",
	},
	"MU": {
		Layout:            "%1\n%2\n%3\n%P\n%L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{3}(?:\\d{2}|[A-Z]{2}\\d{3})",
	},
	"MV": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"MX": {
		Layout:            "%1\n%2\n%3\n%S\n%P %L, %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		SublocalityType:   SublocalityTypeNeighborhood,
		PostalCodePattern: "\\d{5}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AGU", "Aguascalientes", "BCN", "Baja California", "BCS", "Baja California Sur",
			"CAM", "Campeche", "CMX", "Ciudad de México", "COA", "Coahuila",
			"COL", "Colima", "CHP", "Chiapas", "CHH", "Chihuahua",
			"DUG", "Durango", "MEX", "Estado de México", "GUA", "Guanajuato",
			"GRO", "Guerrero", "HID", "Hidalgo", "JAL", "Jalisco",
			"MIC", "Michoacán", "MOR", "Morelos", "NAY", "Nayarit",
			"NLE", "Nuevo León", "OAX", "Oaxaca", "PUE", "Puebla",
			"QUE", "Queretaro", "ROO", "Quintana Roo", "SLP", "San Luis Potosí",
			"SIN", "Sinaloa", "SON", "Sonora", "TAB", "Tabasco",
			"TAM", "Tamaulipas", "TLA", "Tlaxcala", "VER", "Veracruz",
			"YUC", "Yucatán", "ZAC", "Zacatecas",
		),
	},
	"MY": {
		Layout:            "%1\n%2\n%3\n%S\n%P %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		RegionType:        RegionTypeState,
		SublocalityType:   SublocalityTypeVillageTownship,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"01", "Johor", "02", "Kedah", "03", "Kelantan",
			"14", "Kuala Lumpur", "15", "Labuan", "04", "Melaka",
			"05", "Negeri Sembilan", "06", "Pahang", "08", "Perak",
			"09", "Perlis", "07", "Pulau Pinang", "16", "Putrajaya",
			"12", "Sabah", "13", "Sarawak", "10", "Selangor",
			"11", "Terengganu",
		),
	},
	"MZ": {
		Layout:            "%1\n%2\n%3\n%P %L%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
		Regions: NewRegionMap(
			"P", "Cabo Delgado", "MPM", "Cidade de Maputo", "G", "Gaza",
			"I", "Inhambane", "B", "Manica", "L", "Maputo",
			"N", "Nampula", "A", "Niassa", "S", "Sofala",
			"T", "Tete", "Q", "Zambezia",
		),
	},
	"NA": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"NC": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "988\\d{2}",
	},
	"NE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"NF": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "2899",
	},
	"NG": {
		Layout:            "%1\n%2\n%3\n%S\n%L %P\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		RegionType:        RegionTypeState,
		PostalCodePattern: "\\d{6}",
		Regions: NewRegionMap(
			"AB", "Abia", "AD", "Adamawa", "AK", "Akwa Ibom",
			"AN", "Anambra", "BA", "Bauchi", "BY", "Bayelsa",
			"BE", "Benue", "BO", "Borno", "CR", "Cross River",
			"DE", "Delta", "EB", "Ebonyi", "ED", "Edo",
			"EK", "Ekiti", "EN", "Enugu", "FC", "Federal Capital Territory",
			"GO", "Gombe", "IM", "Imo", "JI", "Jigawa",
			"KD", "Kaduna", "KN", "Kano", "KT", "Katsina",
			"KE", "Kebbi", "KO", "Kogi", "KW", "Kwara",
			"LA", "Lagos", "NA", "Nasarawa", "NI", "Niger",
			"OG", "Ogun State", "ON", "Ondo", "OS", "Osun",
			"OY", "Oyo", "PL", "Plateau", "RI", "Rivers",
			"SO", "Sokoto", "TA", "Taraba", "YO", "Yobe",
			"ZA", "Zamfara",
		),
	},
	"NI": {
		Layout:            "%1\n%2\n%3\n%P\n%L, %R",
		Required:          []Field{FieldLine1, FieldLocality},
		RegionType:        RegionTypeDepartment,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"BO", "Boaco", "CA", "Carazo", "CI", "Chinandega",
			"CO", "Chontales", "AN", "Costa Caribe Norte", "AS", "Costa Caribe Sur",
			"ES", "Estelí", "GR", "Granada", "JI", "Jinotega",
			"LE", "León", "MD", "Madriz", "MN", "Managua",
			"MS", "Masaya", "MT", "Matagalpa", "NS", "Nueva Segovia",
			"SJ", "Río San Juan", "RI", "Rivas",
		),
	},
	"NL": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4} ?[A-Z]{2}",
	},
	"NO": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		LocalityType:      LocalityTypePostTown,
		PostalCodePattern: "\\d{4}",
	},
	"NP": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"NR": {
		Layout:     "%1\n%2\n%3\n%R",
		Required:   []Field{FieldLine1, FieldRegion},
		RegionType: RegionTypeDistrict,
		Regions: NewRegionMap(
			"01", "Aiwo", "02", "Anabar", "03", "Anetan",
			"04", "Anibare", "05", "Baiti", "06", "Boe",
			"07", "Buada", "08", "Denigomodu", "09", "Ewa",
			"10", "Ijuw", "11", "Meneng", "12", "Nibok",
			"13", "Uaboe", "14", "Yaren",
		),
	},
	"NZ": {
		Layout:            "%1\n%2\n%3\n%S\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"OM": {
		Layout:            "%1\n%2\n%3\n%P\n%L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "(?:PC )?\\d{3}",
	},
	"PA": {
		Layout:   "%1\n%2\n%3\n%L\n%R",
		Required: []Field{FieldLine1, FieldLocality},
	},
	"PE": {
		Layout:            "%1\n%2\n%3\n%L %P\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		LocalityType:      LocalityTypeDistrict,
		PostalCodePattern: "(?:LIMA \\d{1,2}|CALLAO 0?\\d)|[0-2]\\d{4}",
		Regions: NewRegionMap(
			"AMA", "Amazonas", "ANC", "Ancash", "APU", "Apurimac",
			"ARE", "Arequipa", "AYA", "Ayacucho", "CAJ", "Cajamarca",
			"CAL", "Callao", "CUS", "Cusco", "HUV", "Huancavelica",
			"HUC", "Huanuco", "ICA", "Ica", "JUN", "Junin",
			"LAL", "La Libertad", "LAM", "Lambayeque", "LIM", "Lima",
			"LOR", "Loreto", "MDD", "Madre de Dios", "MOQ", "Moquegua",
			"LMA", "Municipalidad Metropolitana de Lima", "PAS", "Pasco", "PIU", "Piura",
			"PUN", "Puno", "SAM", "San Martin", "TAC", "Tacna",
			"TUM", "Tumbes", "UCA", "Ucayali",
		),
	},
	"PF": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeIsland,
		PostalCodePattern: "987\\d{2}",
	},
	"PG": {
		Layout:            "%1\n%2\n%3\n%L %P %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		PostalCodePattern: "\\d{3}",
	},
	"PH": {
		Layout:            "%1\n%2\n%3\n%S, %L\n%P %R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
		Regions: NewRegionMap(
			"ABR", "Abra", "AGN", "Agusan del Norte", "AGS", "Agusan del Sur",
			"AKL", "Aklan", "ALB", "Albay", "ANT", "Antique",
			"APA", "Apayao", "AUR", "Aurora", "BAS", "Basilan",
			"BAN", "Bataan", "BTN", "Batanes", "BTG", "Batangas",
			"BEN", "Benguet", "BIL", "Biliran", "BOH", "Bohol",
			"BUK", "Bukidnon", "BUL", "Bulacan", "CAG", "Cagayan",
			"CAN", "Camarines Norte", "CAS", "Camarines Sur", "CAM", "Camiguin",
			"CAP", "Capiz", "CAT", "Catanduanes", "CAV", "Cavite",
			"CEB", "Cebu", "NCO", "Cotabato", "COM", "Davao de Oro",
			"DAV", "Davao del Norte", "DAS", "Davao del Sur", "DVO", "Davao Occidental",
			"DAO", "Davao Oriental", "DIN", "Dinagat Islands", "EAS", "Eastern Samar",
			"GUI", "Guimaras", "IFU", "Ifugao", "ILN", "Ilocos Norte",
			"ILS", "Ilocos Sur", "ILI", "Iloilo", "ISA", "Isabela",
			"KAL", "Kalinga", "LUN", "La Union", "LAG", "Laguna",
			"LAN", "Lanao del Norte", "LAS", "Lanao del Sur", "LEY", "Leyte",
			"MAG", "Maguindanao", "MAD", "Marinduque", "MAS", "Masbate",
			"00", "Metro Manila", "MDC", "Mindoro Occidental", "MDR", "Mindoro Oriental",
			"MSC", "Misamis Occidental", "MSR", "Misamis Oriental", "MOU", "Mountain Province",
			"NEC", "Negros Occidental", "NER", "Negros Oriental", "NSA", "Northern Samar",
			"NUE", "Nueva Ecija", "NUV", "Nueva Vizcaya", "PLW", "Palawan",
			"PAM", "Pampanga", "PAN", "Pangasinan", "QUE", "Quezon Province",
			"QUI", "Quirino", "RIZ", "Rizal", "ROM", "Romblon",
			"WSA", "Samar", "SAR", "Sarangani", "SIG", "Siquijor",
			"SOR", "Sorsogon", "SCO", "South Cotabato", "SLE", "Southern Leyte",
			"SUK", "Sultan Kudarat", "SLU", "Sulu", "SUN", "Surigao del Norte",
			"SUR", "Surigao del Sur", "TAR", "Tarlac", "TAW", "Tawi-Tawi",
			"ZMB", "Zambales", "ZAN", "Zamboanga del Norte", "ZAS", "Zamboanga del Sur",
			"ZSI", "Zamboanga Sibuguey",
		),
	},
	"PK": {
		Layout:            "%1\n%2\n%3\n%L-%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"PL": {
		Layout: "%1\n%2\n%3\n%P %L",
		Required: []Field{
			FieldLine1, FieldLocality, FieldPostalCode,
		},
		PostalCodePattern: "\\d{2}-\\d{3}",
	},
	"PM": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78]5\\d{2}",
	},
	"PN": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "PCRN 1ZZ",
	},
	"PR": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(00[679]\\d{2})(?:[ \\-](\\d{4}))?",
	},
	"PT": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}-\\d{3}",
	},
	"PW": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(969(?:39|40))(?:[ \\-](\\d{4}))?",
	},
	"PY": {
		Layout:            "%1\n%2\n%3\n%P %L",
		PostalCodePattern: "\\d{4}",
	},
	"RE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "9[78]4\\d{2}",
	},
	"RO": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{6}",
	},
	"RS": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5,6}",
	},
	"RU": {
		Layout:            "%1\n%2\n%3\n%L\n%R\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeOblast,
		PostalCodePattern: "\\d{6}",
		Regions: NewRegionMap(
			"AD", "Adygeya, Respublika", "AL", "Altay, Respublika", "ALT", "Altayskiy kray",
			"AMU", "Amurskaya oblast", "ARK", "Arkhangelskaya oblast", "AST", "Astrakhanskaya oblast",
			"BA", "Bashkortostan, Respublika", "BEL", "Belgorodskaya oblast", "BRY", "Bryanskaya oblast",
			"BU", "Buryatiya, Respublika", "CE", "Chechenskaya Respublika", "CHE", "Chelyabinskaya oblast",
			"CHU", "Chukotskiy avtonomnyy okrug", "CU", "Chuvashskaya Respublika", "DA", "Dagestan, Respublika",
			"IN", "Ingushetiya, Respublika", "IRK", "Irkutskaya oblast", "IVA", "Ivanovskaya oblast",
			"KB", "Kabardino-Balkarskaya Respublika", "KGD", "Kaliningradskaya oblast", "KL", "Kalmykiya, Respublika",
			"KLU", "Kaluzhskaya oblast", "KAM", "Kamchatskiy kray", "KC", "Karachayevo-Cherkesskaya Respublika",
			"KR", "Kareliya, Respublika", "KEM", "Kemerovskaya oblast", "KHA", "Khabarovskiy kray",
			"KK", "Khakasiya, Respublika", "KHM", "Khanty-Mansiyskiy avtonomnyy okrug-Yugra", "KIR", "Kirovskaya oblast",
			"KO", "Komi, Respublika", "KOS", "Kostromskaya oblast", "KDA", "Krasnodarskiy kray",
			"KYA", "Krasnoyarskiy kray", "KGN", "Kurganskaya oblast", "KRS", "Kurskaya oblast",
			"LEN", "Leningradskaya oblast", "LIP", "Lipetskaya oblast", "MAG", "Magadanskaya oblast",
			"ME", "Mariy El, Respublika", "MO", "Mordoviya, Respublika", "MOS", "Moskovskaya oblast",
			"MOW", "Moskva", "MUR", "Murmanskaya oblast", "NEN", "Nenetskiy avtonomnyy okrug",
			"NIZ", "Nizhegorodskaya oblast", "NGR", "Novgorodskaya oblast", "NVS", "Novosibirskaya oblast",
			"OMS", "Omskaya oblast", "ORE", "Orenburgskaya oblast", "ORL", "Orlovskaya oblast",
			"PNZ", "Penzenskaya oblast", "PER", "Permskiy kray", "PRI", "Primorskiy kray",
			"PSK", "Pskovskaya oblast", "ROS", "Rostovskaya oblast", "RYA", "Ryazanskaya oblast",
			"SA", "Sakha, Respublika [Yakutiya]", "SAK", "Sakhalinskaya oblast", "SAM", "Samarskaya oblast",
			"SPE", "Sankt-Peterburg", "SAR", "Saratovskaya oblast", "SE", "Severnaya Osetiya - Alaniya, Respublika",
			"SMO", "Smolenskaya oblast", "STA", "Stavropolskiy kray", "SVE", "Sverdlovskaya oblast",
			"TAM", "Tambovskaya oblast", "TA", "Tatarstan, Respublika", "TOM", "Tomskaya oblast",
			"TUL", "Tulskaya oblast", "TVE", "Tverskaya oblast", "TYU", "Tyumenskaya oblast",
			"TY", "Tyva, Respublika [Tuva]", "UD", "Udmurtskaya Respublika", "ULY", "Ulyanovskaya oblast",
			"VLA", "Vladimirskaya oblast", "VGG", "Volgogradskaya oblast", "VLG", "Vologodskaya oblast",
			"VOR", "Voronezhskaya oblast", "YAN", "Yamalo-Nenetskiy avtonomnyy okrug", "YAR", "Yaroslavskaya oblast",
			"YEV", "Yevreyskaya avtonomnaya oblast", "ZAB", "Zabaykalskiy kray",
		),
		LocalRegions: NewRegionMap(
			"ALT", "Алтайский край", "AMU", "Амурская область", "ARK", "Архангельская область",
			"AST", "Астраханская область", "BEL", "Белгородская область", "BRY", "Брянская область",
			"VLA", "Владимирская область", "VGG", "Волгоградская область", "VLG", "Вологодская область",
			"VOR", "Воронежская область", "YEV", "Еврейская автономная область", "ZAB", "Забайкальский край",
			"IVA", "Ивановская область", "IRK", "Иркутская область", "KB", "Кабардино-Балкарская Республика",
			"KGD", "Калининградская область", "KLU", "Калужская область", "KAM", "Камчатский край",
			"KC", "Карачаево-Черкесская Республика", "KEM", "Кемеровская область", "KIR", "Кировская область",
			"KOS", "Костромская область", "KDA", "Краснодарский край", "KYA", "Красноярский край",
			"KGN", "Курганская область", "KRS", "Курская область", "LEN", "Ленинградская область",
			"LIP", "Липецкая область", "MAG", "Магаданская область", "MOW", "Москва",
			"MOS", "Московская область", "MUR", "Мурманская область", "NEN", "Ненецкий автономный округ",
			"NIZ", "Нижегородская область", "NGR", "Новгородская область", "NVS", "Новосибирская область",
			"OMS", "Омская область", "ORE", "Оренбургская область", "ORL", "Орловская область",
			"PNZ", "Пензенская область", "PER", "Пермский край", "PRI", "Приморский край",
			"PSK", "Псковская область", "AD", "Республика Адыгея", "AL", "Республика Алтай",
			"BA", "Республика Башкортостан", "BU", "Республика Бурятия", "DA", "Республика Дагестан",
			"IN", "Республика Ингушетия", "KL", "Республика Калмыкия", "KR", "Республика Карелия",
			"KO", "Республика Коми", "ME", "Республика Марий Эл", "MO", "Республика Мордовия",
			"SA", "Республика Саха (Якутия)", "SE", "Республика Северная Осетия-Алания", "TA", "Республика Татарстан",
			"TY", "Республика Тыва", "UD", "Республика Удмуртия", "KK", "Республика Хакасия",
			"ROS", "Ростовская область", "RYA", "Рязанская область", "SAM", "Самарская область",
			"SPE", "Санкт-Петербург", "SAR", "Саратовская область", "SAK", "Сахалинская область",
			"SVE", "Свердловская область", "SMO", "Смоленская область", "STA", "Ставропольский край",
			"TAM", "Тамбовская область", "TVE", "Тверская область", "TOM", "Томская область",
			"TUL", "Тульская область", "TYU", "Тюменская область", "ULY", "Ульяновская область",
			"KHA", "Хабаровский край", "KHM", "Ханты-Мансийский автономный округ", "CHE", "Челябинская область",
			"CE", "Чеченская Республика", "CU", "Чувашская Республика", "CHU", "Чукотский автономный округ",
			"YAN", "Ямало-Ненецкий автономный округ", "YAR", "Ярославская область",
		),
	},
	"SA": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"SC": {
		Layout:     "%1\n%2\n%3\n%L\n%R",
		Required:   []Field{FieldLine1, FieldLocality},
		RegionType: RegionTypeIsland,
	},
	"SD": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		LocalityType:      LocalityTypeDistrict,
		PostalCodePattern: "\\d{5}",
	},
	"SE": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		LocalityType:      LocalityTypePostTown,
		PostalCodePattern: "\\d{3} ?\\d{2}",
	},
	"SG": {
		Layout:            "%1\n%2\n%3\n%P",
		Required:          []Field{FieldLine1, FieldPostalCode},
		PostalCodePattern: "\\d{6}",
	},
	"SH": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "(?:ASCN|STHL) 1ZZ",
	},
	"SI": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"SJ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		LocalityType:      LocalityTypePostTown,
		PostalCodePattern: "\\d{4}",
	},
	"SK": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{3} ?\\d{2}",
	},
	"SM": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldPostalCode},
		PostalCodePattern: "4789\\d",
	},
	"SN": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
	"SO": {
		Layout:            "%1\n%2\n%3\n%L, %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		PostalCodePattern: "[A-Z]{2} ?\\d{5}",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AW", "Awdal", "BK", "Bakool", "BN", "Banaadir",
			"BR", "Bari", "BY", "Bay", "GA", "Galguduud",
			"GE", "Gedo", "HI", "Hiiraan", "JD", "Jubbada Dhexe",
			"JH", "Jubbada Hoose", "MU", "Mudug", "NU", "Nugaal",
			"SA", "Sanaag", "SD", "Shabeellaha Dhexe", "SH", "Shabeellaha Hoose",
			"SO", "Sool", "TO", "Togdheer", "WO", "Woqooyi Galbeed",
		),
	},
	"SR": {
		Layout:   "%1\n%2\n%3\n%L\n%R",
		Required: []Field{FieldLine1, FieldLocality},
		Regions: NewRegionMap(
			"BR", "Brokopondo", "CM", "Commewijne", "CR", "Coronie",
			"MA", "Marowijne", "NI", "Nickerie", "PR", "Para",
			"PM", "Paramaribo", "SA", "Saramacca", "SI", "Sipaliwini",
			"WA", "Wanica",
		),
	},
	"SV": {
		Layout:            "%1\n%2\n%3\n%P-%L\n%R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		PostalCodePattern: "CP [1-3][1-7][0-2]\\d",
		Regions: NewRegionMap(
			"AH", "Ahuachapán", "CA", "Cabañas", "CH", "Chalatenango",
			"CU", "Cuscatlán", "LI", "La Libertad", "PA", "La Paz",
			"UN", "La Unión", "MO", "Morazán", "SM", "San Miguel",
			"SS", "San Salvador", "SV", "San Vicente", "SA", "Santa Ana",
			"SO", "Sonsonate", "US", "Usulután",
		),
	},
	"SY": {
		Layout:       "%1\n%2\n%3\n%L",
		Required:     []Field{FieldLine1, FieldLocality},
		LocalityType: LocalityTypeDistrict,
	},
	"SZ": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "[HLMS]\\d{3}",
	},
	"TA": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "TDCU 1ZZ",
	},
	"TC": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "TKCA 1ZZ",
	},
	"TH": {
		Locale:            Locale{Language: "th"},
		Layout:            "%1\n%2\n%3\n%S, %L\n%R %P",
		LocalLayout:       "%1\n%2\n%3\n%S %L\n%R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"37", "Amnat Charoen", "15", "Ang Thong", "10", "Bangkok",
			"38", "Bueng Kan", "31", "Buri Ram", "24", "Chachoengsao",
			"18", "Chai Nat", "36", "Chaiyaphum", "22", "Chanthaburi",
			"50", "Chiang Mai", "57", "Chiang Rai", "20", "Chon Buri",
			"86", "Chumpon", "46", "Kalasin", "62", "Kamphaeng Phet",
			"71", "Kanchanaburi", "40", "Khon Kaen", "81", "Krabi",
			"52", "Lampang", "51", "Lamphun", "42", "Loei",
			"16", "Lop Buri", "58", "Mae Hong Son", "44", "Maha Sarakham",
			"49", "Mukdahan", "26", "Nakhon Nayok", "73", "Nakhon Pathom",
			"48", "Nakhon Phanom", "30", "Nakhon Ratchasima", "60", "Nakhon Sawan",
			"80", "Nakhon Si Thammarat", "55", "Nan", "96", "Narathiwat",
			"39", "Nong Bua Lam Phu", "43", "Nong Khai", "12", "Nonthaburi",
			"13", "Pathum Thani", "94", "Pattani", "82", "Phang Nga",
			"93", "Phattalung", "56", "Phayao", "67", "Phetchabun",
			"76", "Phetchaburi", "66", "Phichit", "65", "Phitsanulok",
			"14", "Phra Nakhon Si Ayutthaya", "54", "Phrae", "83", "Phuket",
			"25", "Prachin Buri", "77", "Prachuap Khiri Khan", "85", "Ranong",
			"70", "Ratchaburi", "21", "Rayong", "45", "Roi Et",
			"27", "Sa Kaeo", "47", "Sakon Nakhon", "11", "Samut Prakan",
			"74", "Samut Sakhon", "75", "Samut Songkhram", "19", "Saraburi",
			"91", "Satun", "33", "Si Sa Ket", "17", "Sing Buri",
			"90", "Songkhla", "64", "Sukhothai", "72", "Suphanburi",
			"84", "Surat Thani", "32", "Surin", "63", "Tak",
			"92", "Trang", "23", "Trat", "34", "Ubon Ratchathani",
			"41", "Udon Thani", "61", "Uthai Thani", "53", "Uttaradit",
			"95", "Yala", "35", "Yasothon",
		),
		LocalRegions: NewRegionMap(
			"81", "กระบี่", "10", "กรุงเทพมหานคร", "71", "กาญจนบุรี",
			"46", "กาฬสินธุ์", "62", "กำแพงเพชร", "40", "ขอนแก่น",
			"38", "จังหวัด บึงกาฬ", "22", "จันทบุรี", "24", "ฉะเชิงเทรา",
			"20", "ชลบุรี", "18", "ชัยนาท", "36", "ชัยภูมิ",
			"86", "ชุมพร", "57", "เชียงราย", "50", "เชียงใหม่",
			"92", "ตรัง", "23", "ตราด", "63", "ตาก",
			"26", "นครนายก", "73", "นครปฐม", "48", "นครพนม",
			"30", "นครราชสีมา", "80", "นครศรีธรรมราช", "60", "นครสวรรค์",
			"12", "นนทบุรี", "96", "นราธิวาส", "55", "น่าน",
			"31", "บุรีรัมย์", "13", "ปทุมธานี", "77", "ประจวบคีรีขันธ์",
			"25", "ปราจีนบุรี", "94", "ปัตตานี", "14", "พระนครศรีอยุธยา",
			"56", "พะเยา", "82", "พังงา", "93", "พัทลุง",
			"66", "พิจิตร", "65", "พิษณุโลก", "76", "เพชรบุรี",
			"67", "เพชรบูรณ์", "54", "แพร่", "83", "ภูเก็ต",
			"44", "มหาสารคาม", "49", "มุกดาหาร", "58", "แม่ฮ่องสอน",
			"35", "ยโสธร", "95", "ยะลา", "45", "ร้อยเอ็ด",
			"85", "ระนอง", "21", "ระยอง", "70", "ราชบุรี",
			"16", "ลพบุรี", "52", "ลำปาง", "51", "ลำพูน",
			"42", "เลย", "33", "ศรีสะเกษ", "47", "สกลนคร",
			"90", "สงขลา", "91", "สตูล", "11", "สมุทรปราการ",
			"75", "สมุทรสงคราม", "74", "สมุทรสาคร", "27", "สระแก้ว",
			"19", "สระบุรี", "17", "สิงห์บุรี", "64", "สุโขทัย",
			"72", "สุพรรณบุรี", "84", "สุราษฎร์ธานี", "32", "สุรินทร์",
			"43", "หนองคาย", "39", "หนองบัวลำภู", "15", "อ่างทอง",
			"37", "อำนาจเจริญ", "41", "อุดรธานี", "53", "อุตรดิตถ์",
			"61", "อุทัยธานี", "34", "อุบลราชธานี",
		),
	},
	"TJ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"TM": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"TN": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4}",
	},
	"TR": {
		Layout:            "%1\n%2\n%3\n%P %L/%R",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		LocalityType:      LocalityTypeDistrict,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"01", "Adana", "02", "Adıyaman", "03", "Afyon",
			"04", "Ağrı", "68", "Aksaray", "05", "Amasya",
			"06", "Ankara", "07", "Antalya", "75", "Ardahan",
			"08", "Artvin", "09", "Aydın", "10", "Balıkesir",
			"74", "Bartın", "72", "Batman", "69", "Bayburt",
			"11", "Bilecik", "12", "Bingöl", "13", "Bitlis",
			"14", "Bolu", "15", "Burdur", "16", "Bursa",
			"17", "Çanakkale", "18", "Çankırı", "19", "Çorum",
			"20", "Denizli", "21", "Diyarbakır", "81", "Düzce",
			"22", "Edirne", "23", "Elazığ", "24", "Erzincan",
			"25", "Erzurum", "26", "Eskişehir", "27", "Gaziantep",
			"28", "Giresun", "29", "Gümüşhane", "30", "Hakkari",
			"31", "Hatay", "76", "Iğdır", "32", "Isparta",
			"34", "İstanbul", "35", "İzmir", "46", "Kahramanmaraş",
			"78", "Karabük", "70", "Karaman", "36", "Kars",
			"37", "Kastamonu", "38", "Kayseri", "71", "Kırıkkale",
			"39", "Kırklareli", "40", "Kırşehir", "79", "Kilis",
			"41", "Kocaeli", "42", "Konya", "43", "Kütahya",
			"44", "Malatya", "45", "Manisa", "47", "Mardin",
			"33", "Mersin", "48", "Muğla", "49", "Muş",
			"50", "Nevşehir", "51", "Niğde", "52", "Ordu",
			"80", "Osmaniye", "53", "Rize", "54", "Sakarya",
			"55", "Samsun", "56", "Siirt", "57", "Sinop",
			"58", "Sivas", "63", "Şanlıurfa", "73", "Şırnak",
			"59", "Tekirdağ", "60", "Tokat", "61", "Trabzon",
			"62", "Tunceli", "64", "Uşak", "65", "Van",
			"77", "Yalova", "66", "Yozgat", "67", "Zonguldak",
		),
	},
	"TV": {
		Layout:     "%1\n%2\n%3\n%L\n%R",
		Required:   []Field{FieldLine1, FieldLocality},
		RegionType: RegionTypeIsland,
	},
	"TW": {
		Locale:            Locale{Language: "zh", Script: "Hant"},
		Layout:            "%1\n%2\n%3\n%L, %R %P",
		LocalLayout:       "%P\n%R%L\n%1\n%2\n%3",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeCounty,
		PostalCodePattern: "\\d{3}(?:\\d{2,3})?",
		Regions: NewRegionMap(
			"CHA", "Changhua County", "CYI", "Chiayi City", "CYQ", "Chiayi County",
			"HSZ", "Hsinchu City", "HSQ", "Hsinchu County", "HUA", "Hualien County",
			"KHH", "Kaohsiung City", "KEE", "Keelung City", "KIN", "Kinmen County",
			"LIE", "Lienchiang County", "MIA", "Miaoli County", "NAN", "Nantou County",
			"NWT", "New Taipei City", "PEN", "Penghu County", "PIF", "Pingtung County",
			"TXG", "Taichung City", "TNN", "Tainan City", "TPE", "Taipei City",
			"TTT", "Taitung County", "TAO", "Taoyuan County", "ILA", "Yilan County",
			"YUN", "Yunlin County",
		),
		LocalRegions: NewRegionMap(
			"TXG", "台中市", "TPE", "台北市", "TTT", "台東縣",
			"TNN", "台南市", "ILA", "宜蘭縣", "HUA", "花蓮縣",
			"KIN", "金門縣", "NAN", "南投縣", "PIF", "屏東縣",
			"MIA", "苗栗縣", "TAO", "桃園市", "KHH", "高雄市",
			"KEE", "基隆市", "LIE", "連江縣", "YUN", "雲林縣",
			"NWT", "新北市", "HSZ", "新竹市", "HSQ", "新竹縣",
			"CYI", "嘉義市", "CYQ", "嘉義縣", "CHA", "彰化縣",
			"PEN", "澎湖縣",
		),
	},
	"TZ": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{4,5}",
	},
	"UA": {
		Locale:            Locale{Language: "uk"},
		Layout:            "%1\n%2\n%3\n%L\n%R\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		RegionType:        RegionTypeOblast,
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"43", "Avtonomna Respublika Krym", "71", "Cherkaska oblast", "74", "Chernihivska oblast",
			"77", "Chernivetska oblast", "12", "Dnipropetrovska oblast", "14", "Donetska oblast",
			"26", "Ivano-Frankivska oblast", "63", "Kharkivska oblast", "65", "Khersonska oblast",
			"68", "Khmelnytska oblast", "35", "Kirovohradska oblast", "30", "Kyiv",
			"32", "Kyivska oblast", "09", "Luhanska oblast", "46", "Lvivska oblast",
			"48", "Mykolaivska oblast", "51", "Odeska oblast", "53", "Poltavska oblast",
			"56", "Rivnenska oblast", "40", "Sevastopol", "59", "Sumska oblast",
			"61", "Ternopilska oblast", "05", "Vinnytska oblast", "07", "Volynska oblast",
			"21", "Zakarpatska oblast", "23", "Zaporizka oblast", "18", "Zhytomyrska oblast",
		),
		LocalRegions: NewRegionMap(
			"43", "Автономна Республіка Крим", "05", "Вінницька область", "07", "Волинська область",
			"12", "Дніпропетровська область", "14", "Донецька область", "18", "Житомирська область",
			"21", "Закарпатська область", "23", "Запорізька область", "26", "Івано-Франківська область",
			"30", "Київ", "32", "Київська область", "35", "Кіровоградська область",
			"09", "Луганська область", "46", "Львівська область", "48", "Миколаївська область",
			"51", "Одеська область", "53", "Полтавська область", "56", "Рівненська область",
			"40", "Севастополь", "59", "Сумська область", "61", "Тернопільська область",
			"63", "Харківська область", "65", "Херсонська область", "68", "Хмельницька область",
			"71", "Черкаська область", "77", "Чернівецька область", "74", "Чернігівська область",
		),
	},
	"UM": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "96898",
	},
	"US": {
		Layout:            "%1\n%2\n%3\n%L, %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(\\d{5})(?:[ \\-](\\d{4}))?",
		ShowRegionID:      true,
		Regions: NewRegionMap(
			"AL", "Alabama", "AK", "Alaska", "AS", "American Samoa",
			"AZ", "Arizona", "AR", "Arkansas", "AA", "Armed Forces (AA)",
			"AE", "Armed Forces (AE)", "AP", "Armed Forces (AP)", "CA", "California",
			"CO", "Colorado", "CT", "Connecticut", "DE", "Delaware",
			"DC", "District of Columbia", "FL", "Florida", "GA", "Georgia",
			"GU", "Guam", "HI", "Hawaii", "ID", "Idaho",
			"IL", "Illinois", "IN", "Indiana", "IA", "Iowa",
			"KS", "Kansas", "KY", "Kentucky", "LA", "Louisiana",
			"ME", "Maine", "MH", "Marshall Islands", "MD", "Maryland",
			"MA", "Massachusetts", "MI", "Michigan", "FM", "Micronesia",
			"MN", "Minnesota", "MS", "Mississippi", "MO", "Missouri",
			"MT", "Montana", "NE", "Nebraska", "NV", "Nevada",
			"NH", "New Hampshire", "NJ", "New Jersey", "NM", "New Mexico",
			"NY", "New York", "NC", "North Carolina", "ND", "North Dakota",
			"MP", "Northern Mariana Islands", "OH", "Ohio", "OK", "Oklahoma",
			"OR", "Oregon", "PW", "Palau", "PA", "Pennsylvania",
			"PR", "Puerto Rico", "RI", "Rhode Island", "SC", "South Carolina",
			"SD", "South Dakota", "TN", "Tennessee", "TX", "Texas",
			"UT", "Utah", "VT", "Vermont", "VI", "Virgin Islands",
			"VA", "Virginia", "WA", "Washington", "WV", "West Virginia",
			"WI", "Wisconsin", "WY", "Wyoming",
		),
	},
	"UY": {
		Layout:            "%1\n%2\n%3\n%P %L %R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
		Regions: NewRegionMap(
			"AR", "Artigas", "CA", "Canelones", "CL", "Cerro Largo",
			"CO", "Colonia", "DU", "Durazno", "FS", "Flores",
			"FD", "Florida", "LA", "Lavalleja", "MA", "Maldonado",
			"MO", "Montevideo", "PA", "Paysandú", "RN", "Río Negro",
			"RV", "Rivera", "RO", "Rocha", "SA", "Salto",
			"SJ", "San José", "SO", "Soriano", "TA", "Tacuarembó",
			"TT", "Treinta y Tres",
		),
	},
	"UZ": {
		Layout:            "%1\n%2\n%3\n%P %L\n%R",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{6}",
	},
	"VA": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "00120",
	},
	"VC": {
		Layout:            "%1\n%2\n%3\n%L %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "VC\\d{4}",
	},
	"VE": {
		Layout:            "%1\n%2\n%3\n%L %P, %R",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion},
		RegionType:        RegionTypeState,
		PostalCodePattern: "\\d{4}",
		Regions: NewRegionMap(
			"Z", "Amazonas", "B", "Anzoátegui", "C", "Apure",
			"D", "Aragua", "E", "Barinas", "F", "Bolívar",
			"G", "Carabobo", "H", "Cojedes", "Y", "Delta Amacuro",
			"W", "Dependencias Federales", "A", "Distrito Federal", "I", "Falcón",
			"J", "Guárico", "K", "Lara", "L", "Mérida",
			"M", "Miranda", "N", "Monagas", "O", "Nueva Esparta",
			"P", "Portuguesa", "R", "Sucre", "S", "Táchira",
			"T", "Trujillo", "X", "La Guaira", "U", "Yaracuy",
			"V", "Zulia",
		),
	},
	"VG": {
		Layout:            "%1\n%2\n%3\n%L\n%P",
		Required:          []Field{FieldLine1},
		PostalCodePattern: "VG\\d{4}",
	},
	"VI": {
		Layout:            "%1\n%2\n%3\n%L %R %P",
		Required:          []Field{FieldLine1, FieldLocality, FieldRegion, FieldPostalCode},
		RegionType:        RegionTypeState,
		PostalCodeType:    PostalCodeTypeZip,
		PostalCodePattern: "(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?",
	},
	"VN": {
		Locale:            Locale{Language: "vi"},
		Layout:            "%1\n%2\n%3\n%L\n%R %P",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}\\d?",
		Regions: NewRegionMap(
			"44", "An Giang Province", "43", "Ba Ria-Vung Tau Province", "55", "Bac Lieu Province",
			"54", "Bac Giang Province", "53", "Bac Kan Province", "56", "Bac Ninh Province",
			"50", "Ben Tre Province", "57", "Binh Duong Province", "31", "Binh Dinh Province",
			"58", "Binh Phuoc Province", "40", "Binh Thuan Province", "59", "Ca Mau Province",
			"04", "Cao Bang Province", "CT", "Can Tho City", "DN", "Da Nang City",
			"33", "Dak Lak Province", "72", "Dak Nong Province", "71", "Dien Bien Province",
			"39", "Dong Nai Province", "45", "Dong Thap Province", "30", "Gia Lai Province",
			"03", "Ha Giang Province", "63", "Ha Nam Province", "HN", "Hanoi City",
			"23", "Ha Tinh Province", "61", "Hai Duong Province", "HP", "Haiphong City",
			"73", "Hau Giang Province", "14", "Hoa Binh Province", "66", "Hung Yen Province",
			"34", "Khanh Hoa Province", "47", "Kien Giang Province", "28", "Kon Tum Province",
			"01", "Lai Chau Province", "09", "Lang Song Province", "02", "Lao Cai Province",
			"35", "Lam Dong Province", "41", "Long An Province", "67", "Nam Dinh Province",
			"22", "Nghe An Province", "18", "Ninh Binh Province", "36", "Ninh Thuan Province",
			"68", "Phu Tho Province", "32", "Phu Yen Province", "24", "Quang Binh Province",
			"27", "Quang Nam Province", "29", "Quang Ngai Province", "13", "Quang Ninh Province",
			"25", "Quang Tri Province", "52", "Soc Trang Province", "05", "Son La Province",
			"37", "Tay Ninh Province", "20", "Thai Binh Province", "69", "Thai Nguyen Province",
			"21", "Thanh Hoa Province", "SG", "Ho Chi Minh City", "26", "Thua Thien-Hue Province",
			"46", "Tien Giang Province", "51", "Tra Vinh Province", "07", "Tuyen Quang Province",
			"49", "Vinh Long Province", "70", "Vinh Phuc Province", "06", "Yen Bai Province",
		),
		LocalRegions: NewRegionMap(
			"44", "An Giang", "43", "Bà Rịa–Vũng Tàu", "55", "Bạc Liêu",
			"54", "Bắc Giang", "53", "Bắc Kạn", "56", "Bắc Ninh",
			"50", "Bến Tre", "57", "Bình Dương", "31", "Bình Định",
			"58", "Bình Phước", "40", "Bình Thuận", "59", "Cà Mau",
			"04", "Cao Bằng", "CT", "Cần Thơ", "DN", "Đà Nẵng",
			"33", "Đắk Lắk", "72", "Đăk Nông", "71", "Điện Biên",
			"39", "Đồng Nai", "45", "Đồng Tháp", "30", "Gia Lai",
			"03", "Hà Giang", "63", "Hà Nam", "HN", "Hà Nội",
			"23", "Hà Tĩnh", "61", "Hải Dương", "HP", "Hải Phòng",
			"73", "Hậu Giang", "14", "Hòa Bình", "66", "Hưng Yên",
			"34", "Khánh Hòa", "47", "Kiên Giang", "28", "Kon Tum",
			"01", "Lai Châu", "09", "Lạng Sơn", "02", "Lào Cai",
			"35", "Lâm Đồng", "41", "Long An", "67", "Nam Định",
			"22", "Nghệ An", "18", "Ninh Bình", "36", "Ninh Thuận",
			"68", "Phú Thọ", "32", "Phú Yên", "24", "Quảng Bình",
			"27", "Quảng Nam", "29", "Quảng Ngãi", "13", "Quảng Ninh",
			"25", "Quảng Trị", "52", "Sóc Trăng", "05", "Sơn La",
			"37", "Tây Ninh", "20", "Thái Bình", "69", "Thái Nguyên",
			"21", "Thanh Hóa", "SG", "Thành phố Hồ Chí Minh", "26", "Thừa Thiên–Huế",
			"46", "Tiền Giang", "51", "Trà Vinh", "07", "Tuyên Quang",
			"49", "Vĩnh Long", "70", "Vĩnh Phúc", "06", "Yên Bái",
		),
	},
	"WF": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "986\\d{2}",
	},
	"XK": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "[1-7]\\d{4}",
	},
	"YT": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "976\\d{2}",
	},
	"ZA": {
		Layout:            "%1\n%2\n%3\n%S\n%L\n%P",
		Required:          []Field{FieldLine1, FieldLocality, FieldPostalCode},
		PostalCodePattern: "\\d{4}",
	},
	"ZM": {
		Layout:            "%1\n%2\n%3\n%P %L",
		Required:          []Field{FieldLine1, FieldLocality},
		PostalCodePattern: "\\d{5}",
	},
}
